name: Trigger deploy

on:
  release:
    types: [published, released, updated]
  workflow_dispatch:
    inputs:
      tag:
        default: "beta-1"
        description: "Release tag"
        required: true

env:
  DEFAULT_TAG: "beta-1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        run: |
          curl -X POST \
             -H "Authorization:Bearer ${{ secrets.UPDATE_TOKEN_BETA_1 }}" \
             -H "Content-Type:application/json" \
             -d '{
               "release": "${{ github.event.inputs.tag || env.DEFAULT_TAG }}",
               "commit_sha": "${{ github.sha }}",
               "commit_ref": "${{ github.ref }}"
             }' \
             'https://eye.projectalita.ai/api/v1/alita_ui/ui_ci/administration'
          
